= twitter-metricbot
:icons: font
:toc: macro
:toclevels: 4

image:https://github.com/bmarwell/twitter-metricbot/actions/workflows/maven.yml/badge.svg[Maven CI,link=https://github.com/bmarwell/twitter-metricbot/actions/workflows/maven.yml]
image:https://img.shields.io/badge/License-Apache_2.0-blue.svg[License,link=https://opensource.org/licenses/Apache-2.0]
image:https://codecov.io/gh/bmarwell/twitter-metricbot/branch/main/graph/badge.svg?token=OkJW0qKkJs[codecov.io,link=https://codecov.io/gh/bmarwell/twitter-metricbot]
image:https://img.shields.io/badge/renovate-enabled-brightgreen.svg[Renovate,link=https://renovatebot.com]
image:https://img.shields.io/badge/AppServer-Open%20Liberty-blue[AppServer,link=https://openliberty.io/]

A metric bot for Twitter.
If mentioned with 'please' on a tweet containing imperial units, will reply with converted metric units for your convenience.

== Active bots

* https://twitter.com/metricbot1/with_replies[+🇺🇸 @metricbot1+] on 🐦 Twitter
* https://botsin.space/@metricbot[+🇺🇸 @metricbot@botsin.space+,rel="me"] on 🐘 Mastodon

== How to use

If you spot a tweet with metric units in it, create a reply and mention `@metricbot1 please` or `@metricbot1 convert please`.

For Mastodon, use `@metricbot@botsin.space please` or `@metricbot@botsin.space convert please`.

== Features

* find tweets with imperial units.
* can convert units to metrics and reply.

=== Currently implemented units

.Supported metric conversions in alphabetical order
|===
|Input Unit |Output Unit(s) |Example Input |Example output

|Calories (cal)
|Kilojoule (kJ)
|
|

|Cups (cup)
|Millilitres (ml)
|
|

|Fluid Ounce (fl.oz.)
|Millilitres (ml)
|
|

|Foots and Inches ('/"/ft)
|Centimetres (cm), Metres (m), Kilometres (km)
|
|

|Gallons
|Litres (L), cubic metres (m²)
|
|

|Horse Power (hp)
|Kilowatts (kW)
|
|

|Miles
|Kilometres (km)
|
|

|Pints (pt)
|Litres (L), Millilitres (ml)
|
|

|Pounds (lb)
|Kilograms (kg)
|
|

|Tablespoons (tbsp)
|Grams (g)
|
|

|Teaspoons (tsp)
|Grams (g)
|
|

|Temperature: Degree Fahrenheit (°F)
|Temperature: Degree Celsius (°C)
|
|

|Weighted Ounce (oz.)
|Grams(g)
|
|
|===

No idea what makes the Celsius temperature more metric than Fahrenheit, but Fahrenheit is a very convenient unit.

== Configuration

See https://github.com/bmarwell/twitter-metricbot/wiki/Configuration[Wiki:Configuration].

== How to start

You can start this OpenLiberty docker container like this:

[source,bash]
----
docker run \
  -p 9080:9080 \
  -e IO_GITHUB_BMARWELL_TWITTER_METRICBOT_H2_DB=jdbc:h2:file:/var/opt/metricbot.db \
  -name metricbot \
  io.github.bmarwell.twitter.metricbot/twitter-metricbot-app-ol-docker:latest
----
