CREATE TABLE BSKY_STATUS
(
    STATUS_CID       VARCHAR(128),
    POST_TIME        TIMESTAMP    NOT NULL,
    BOT_RESPONSE_CID VARCHAR(128) NOT NULL DEFAULT '',
    RESPONSE_TIME    TIMESTAMP    NOT NULL,
    PRIMARY KEY (STATUS_CID)
);
