CREATE TABLE BSKY_STATUS
(
    STATUS_ATURI       VARCHAR(256),
    POST_TIME          TIMESTAMP    NOT NULL,
    BOT_RESPONSE_ATURI VARCHAR(256) NOT NULL DEFAULT '',
    RESPONSE_TIME      TIMESTAMP    NOT NULL,
    PRIMARY KEY (STATUS_ATURI)
);
